spring.application.name=ebanx-challenge

# H2 em memória
spring.datasource.url=jdbc:h2:mem:ebanx-challenge-h2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=eric
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Console web (/h2-console)
spring.h2.console.enabled=true
